#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, armEncoder,     sensorRotation)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Add Sonar sensor. 


task main()
{

  while(VexRT[Btn7D] == 0)
  {
  	//Empty while loop. Waits for buton 7D to be pressed to start timer. 
  }

  clearTimer(T1);
  //Regulation time 2:30.
  while(time1[T1] < 180000)
   {
   
  	//Increase or decrease number after slash to make controler more sensitive.
    motor[leftMotor] = VexRT[Ch3] / 1;
    motor[rightMotor] = VexRT[Ch2] / 1;

	if(VexRT[Btn6U] == 1)
    	{
      		motor[armMotor] = 40;
    	}
    else if(VexRT[Btn6D] == 1)
    	{
      		motor[armMotor] = -40;
    	}
    else
    	{
      		motor[armMotor] = 0;
    	}	
	 }
 }
   
   
  //Tells the robot what to do after the script finishes. 
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;

}
